### ISSUE TITLE
final 37

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/monorepo#37]

**Comment by ghost** [comment]
# 💰 Drill Bounty Program 💰

Drill was configured successfully, this issue has an active bounty. [Inspect the transaction](https://explorer.solana.com/tx/4xYVwzikRC2xUGazqxYkU6rTBBu3dMx7pEfqnQYy7xe9UP3R7xtVhgx3eSu8j5W9uuyhYeQMzi45tkDiV6aP7RBs?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer. Below you'll find more details about the Bounty you just created. If you want to get more info about this tool, please read our official doc [here](https://heavyduty.builders/)

---

## 💾 Board info

All about your board.

🔢 **ID**: 409382545.  
🔑 **Public Key**: [7HyJhfxt4kD8FWnzLV2JphcizryTJEznNRbajCvU2RKA](https://explorer.solana.com/address/7HyJhfxt4kD8FWnzLV2JphcizryTJEznNRbajCvU2RKA?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com)  
⏱️ **Lock Time (ms)**:199  
🔒 **Auhtority**:[13i3zyFbtcjEfVuNVR2y21MLHhBabxXbiM8YCqxpTf3E](https://explorer.solana.com/address/13i3zyFbtcjEfVuNVR2y21MLHhBabxXbiM8YCqxpTf3E?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com)

&nbsp;

## 🏦 Bounty info

All about your new bounty.

🔢 **ID**: 37.  
🔑 **Public Key**: [BYGwY7jNTsfTAEVNfMKkdRpeMA2vby8Bnhmk9mCjXUt1](https://explorer.solana.com/address/BYGwY7jNTsfTAEVNfMKkdRpeMA2vby8Bnhmk9mCjXUt1?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com)  
🧰 **Vault ATA**:[4SiA161deKjj9kfnmZE6QPpSLGGfEJFyL1a6mgSWBEUW](https://explorer.solana.com/address/4SiA161deKjj9kfnmZE6QPpSLGGfEJFyL1a6mgSWBEUW?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com)

> _You can use this information and our CLI to fetch more detailed data, like the Bump and others solana detail you may need in some cases._

---

## 🤳 Solana pay

Use the following QR to send funds to bounty vault, please be sure what you are doing before make the transfer, this can't be undone.

![Solana pay QR](https://raw.githubusercontent.com/andresmgsl/monorepo/master/.drill/37.jpg)

### 🪙💵 **CURRENT DEPOSIT AMOUNT: 0** 💵🪙
---

## 🚨 Disclaimer

_PLEASE BE SURE YOU KNOW THIS REPO AND ALREADY SPOKE WITH SOME ADMIN. IS IMPORTANT TO KEEP IN MIND that THIS COMMENT (INCLUDING THE ADDRESS AND THE QR IMAGE) CAN BE MODIFIED FOR ANY PERSON WITH THE SUFFICIENT PRIVILEGE IN THIS REPO. DRILL NOR HEAVYDUTY BE RESPONSIBLE FOR ANY SCAM OR BAD USE OF THIS SOFTWARE._
